### ISSUE TITLE
Breaks colors in terminal

### ISSUE THREAD

**Issue by adrianstaniec** [valignatev/heaven-and-hell#6]
Your package works very nicely in graphical mode,
but it breaks the theme 256color look in the terminal,
compared to just (load-theme '<theme-name> t)
seen on emacs 25.3

**Comment by valignatev** [comment]
Thanks for the report! Honestly, I never tested it in the terminal :)
I'll try to fix it. Can you also tell me what themes have you tried?

**Comment by valignatev** [comment]
I've tried spacemacs light/dark, they seem to work fine.

**Comment by valignatev** [comment]
Also, I'm interested in what terminal emulator you're using and if it has true color support

**Comment by adrianstaniec** [comment]
I'm sorry, I think the problem is with the theme not you package.

I was trying with solarized-dark, and indeed just loading with on startup with load-theme works,
and doing it via your package not, but I get the same problem when loading that theme with counsel-load-theme, so I blame it on the theme now

To answer your question, i am using st, but that should matter.

**Comment by valignatev** [comment]
Glad that you've sorted that out :+1:
