### ISSUE TITLE
How can I change the background color of only the dark theme?

### ISSUE THREAD

**Issue by deescuderoo** [valignatev/heaven-and-hell#8]
Thanks :)

**Comment by valignatev** [comment]
Hi! Thanks for submitting an issue!
Can you explain your use case s bit more?
You want to cycle only between two dark themes? Without light one?

**Comment by deescuderoo** [comment]
Yes, sorry for the lack of detail. Before your theme I was using [cyberpunk theme](https://github.com/n3mo/cyberpunk-theme.el). I switched to yours because of the easy switch between dark and light themes, but for the dark one I still prefer cyberpunk to be honest (especially since the background is darker). So I was thinking of changing your dark theme colors to mimic cyberpunk's ones. 

It would be actually better if I could use cyberpunk directly for the dark theme, and your light one for well... the light one. Do you think this is possible?

Thanks!

**Comment by valignatev** [comment]
Ok, I think I get it. heaven-and-hell doesn't make any assumptions or requirements about your themes, so you can put any theme you have installed in the settings :)

Let's say you have cyberpunk theme installed. You can configure it then as your dark theme:
```elisp
(setq heaven-and-hell-themes
        '((light . some-theme)
          (dark . cyberpunk)))
```

And it should work. I, for example, use spacemacs dark and light themes which I install separately, here's my config for `heaven-and-hell`: https://github.com/valignatev/dotfiles/blob/master/.emacs.d/init.el#L100-L101:
```elisp
(setq heaven-and-hell-themes
        '((light . spacemacs-light)
          (dark . spacemacs-dark)))
```
Hope it'll shed some light on this and will be helpful

**Comment by deescuderoo** [comment]
Oh I see! That makes sense. I will test that once I am in my computer and I will let you know. Thanks for the nice help! :)

**Comment by valignatev** [comment]
I'll close this one. Let me know if you still have questions/issues.
